export const clerkAppearance = {
  variables: {
    colorPrimary: '#6366F1',
    colorBackground: 'var(--color-surface)',
    colorText: 'var(--color-primary)',
    colorTextSecondary: 'var(--color-secondary)',
    colorInputBackground: 'var(--color-bg)',
    colorInputText: 'var(--color-primary)',
    colorInputBorder: 'var(--color-input-border)',
    colorDanger: '#f87171',
    colorSuccess: '#34d399',
    borderRadius: '0.75rem',
    fontFamily: 'inherit',
  },
  elements: {
    rootBox: 'w-full max-w-full flex justify-center',
    cardBox: 'w-full max-w-full shadow-none border-0 bg-transparent p-0 m-0',
    pageScrollBox: 'p-0 m-0',
    scrollBox: 'p-0 m-0',
    card: 'w-full max-w-full bg-transparent border-0 shadow-none p-0 m-0',
    header: 'hidden',
    headerTitle: 'hidden',
    headerSubtitle: 'hidden',
    socialButtonsBlockButton:
      'bg-theme-bg border border-theme-border text-theme-primary hover:border-theme-primary/40 rounded-xl font-semibold transition-all h-12',
    formButtonPrimary:
      'bg-theme-accent text-white font-bold rounded-xl hover:opacity-90 transition-all h-12 shadow-lg',
    formFieldInput:
      'bg-theme-bg text-theme-primary text-base sm:text-lg px-4 rounded-xl focus:ring-2 focus:ring-theme-accent outline-none h-12 sm:h-14 placeholder:!text-theme-secondary/50',
    formFieldLabel: 'text-theme-primary font-medium text-sm',
    footerActionLink: 'text-theme-accent font-bold hover:underline',
    dividerLine: 'bg-theme-border',
    dividerText: 'text-theme-secondary text-xs',
    identityPreviewText: 'text-theme-primary',
    identityPreviewEditButton: 'text-theme-accent',
    alertText: 'text-theme-error-text text-sm',
    userButtonAvatarBox: 'w-9 h-9 rounded-full',
    userButtonPopoverCard: 'bg-theme-surface border border-theme-border rounded-2xl shadow-xl',
    userButtonPopoverActionButton: 'text-theme-primary hover:bg-theme-bg rounded-xl',
    userButtonPopoverActionButtonText: 'text-theme-primary text-sm font-medium',
    userButtonPopoverFooter: 'hidden',
    footer: 'hidden',
    footerAction: 'hidden',
    footerActionText: 'text-theme-secondary',
    formFieldRow: 'gap-2',
    formResendCodeLink: 'text-theme-accent font-bold hover:underline',
    formHeaderTitle: 'hidden',
    formHeaderSubtitle: 'hidden',
    socialButtonsProviderIcon: 'w-5 h-5',
    socialButtonsIconButton: 'border-0 shadow-none',
    otpCodeFieldInput: '!bg-theme-bg rounded-xl text-theme-primary text-lg font-bold h-12 sm:h-14',
    checkbox: '[&_input]:!bg-theme-bg [&_input]:!border-theme-border [&_input:checked]:!bg-theme-accent [&_input:checked]:!border-theme-accent',
    checkboxLabel: '!text-theme-secondary text-sm',
    formFieldInfoText: '!text-theme-secondary text-xs',
    formFieldWarningText: '!text-yellow-500 text-xs',
    formFieldSuccessText: '!text-theme-success-text text-xs',
    formFieldErrorText: '!text-theme-error-text text-xs',
    formFieldHintText: '!text-theme-secondary text-xs',
    formFieldAction: '!text-theme-accent font-medium hover:underline',
    tagInputContainer: 'bg-theme-bg border border-theme-border rounded-xl',
    activeDeviceListItem: 'bg-theme-bg border border-theme-border rounded-xl',
    activeDevice: '!text-theme-primary',
    activeDeviceLabel: '!text-theme-secondary',
  },
}
